### ISSUE TITLE
I am getting all pages and css and js files in the posts page in CMS plugin

### ISSUE THREAD

**Issue by sulthan-betabulls** [SteveMcArthur/docpad-plugin-cms#10]
i am getting all pages and css and js files in the posts page in CMS plugin.Can you tell me where to put my blog folder.i have Layouts, render, and static folders in src folder. Is there any particular folder structure for blog.

**Comment by SteveMcArthur** [comment]
I'm not sure what you are asking here. The plugin contains a folder which houses the html, css, image and javascript for the presentational aspects of the cms - a template folder.  Like a DocPad project these files are divided between a "layouts", "static" and "render" folders. The contents of these folders are copied across to your DocPad project, but in a "cms" sub-folder. That is: "layouts/cms", "static/cms", "render/cms". Your DocPad project itself can have any folder structure it wants - the cms plugin is independent of that.

**Comment by sulthan-betabulls** [comment]
Hi i am getting the following screen when i click on posts link in sidebar menu. All css and js and pages coming in posts page.
![screencapture-localhost-9778-cms-posts-1505108745289](https://user-images.githubusercontent.com/31244127/30260349-77fde7ca-96e4-11e7-850c-48b6b28cd872.png)
